---
title: "Codebook"
author: '@toplusplus'
date: "August 6, 2017"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Codebook
### Cleaning Up Sensor Data From Samsung Galaxy S

Over the original dataset, available here: [Human Activity Recognition Using Smartphones Dataset](https://archive.ics.uci.edu/ml/datasets/human+activity+recognition+using+smartphones), it was created an independent tidy data set applying the following the steps: 

1. Omit the pre-processed signal data and load only the vectors of features, the subjects and the activities data. 
2. Merge both training and test sets into one dataset.
3. Extract only the measurements on the mean and standard deviation for each measurement. 
4. Substitute the factor names of the activities with its corresponding descriptive names.
5. Label the dataset variables with descriptive and syntactically valid names.
6. Summarize using the average of each variable for each activity and each subject.

For a detailed description of the **data wrangling process** applied please consult: [Cleaning Up Sensor Data From Samsung Galaxy S](https://github.com/toplusplus/getandclean/blob/master/Cleaning_Up_Sensor_Data_From_Samsung_Galaxy_S.md).

The dataset created it's called **avgdata**. It contains **180 observations** and **68 variables**. 

The **first 2 variables** are: 

**"activity"**: identify the six activities performed by the subjects (walking, walking_upstairs, walking_downstairs, sitting, standing, laying).

**"subject"**: identify the subject who performed the activity for each window sample. Its range is from 1 to 30.

The remaining **66 variables** correspond to the the average calculated for each activity and each subject of that particular feature. A detailed description of each feature is in the **features_info.txt** file in the original dataset. 

The remaining variables names are list below: 

**"tBodyAcc_mean_X"**  
**"tBodyAcc_mean_X"**  
**"tBodyAcc_mean_Y"**  
**"tBodyAcc_mean_Z"**  
**"tBodyAcc_std_X"**  
**"tBodyAcc_std_Y"**  
**"tBodyAcc_std_Z"**  
**"tGravityAcc_mean_X"**  
**"tGravityAcc_mean_Y"**  
**"tGravityAcc_mean_Z"**  
**"tGravityAcc_std_X"**  
**"tGravityAcc_std_Y"**  
**"tGravityAcc_std_Z"**  
**"tBodyAccJerk_mean_X"**  
**"tBodyAccJerk_mean_Y"**  
**"tBodyAccJerk_mean_Z"**  
**"tBodyAccJerk_std_X"**  
**"tBodyAccJerk_std_Y"**  
**"tBodyAccJerk_std_Z"**  
**"tBodyGyro_mean_X"**  
**"tBodyGyro_mean_Y"**  
**"tBodyGyro_mean_Z"**  
**"tBodyGyro_std_X"**  
**"tBodyGyro_std_Y"**  
**"tBodyGyro_std_Z"**  
**"tBodyGyroJerk_mean_X"**  
**"tBodyGyroJerk_mean_Y"**  
**"tBodyGyroJerk_mean_Z"**  
**"tBodyGyroJerk_std_X"**  
**"tBodyGyroJerk_std_Y"**  
**"tBodyGyroJerk_std_Z"**  
**"tBodyAccMag_mean"**  
**"tBodyAccMag_std"**  
**"tGravityAccMag_mean"**  
**"tGravityAccMag_std"**  
**"tBodyAccJerkMag_mean"**  
**"tBodyAccJerkMag_std"**  
**"tBodyGyroMag_mean"**  
**"tBodyGyroMag_std"**  
**"tBodyGyroJerkMag_mean"**  
**"tBodyGyroJerkMag_std"**  
**"fBodyAcc_mean_X"**  
**"fBodyAcc_mean_Y"**  
**"fBodyAcc_mean_Z"**  
**"fBodyAcc_std_X"**  
**"fBodyAcc_std_Y"**  
**"fBodyAcc_std_Z"**        
**"fBodyAccJerk_mean_X"**  
**"fBodyAccJerk_mean_Y"**  
**"fBodyAccJerk_mean_Z"**  
**"fBodyAccJerk_std_X"**  
**"fBodyAccJerk_std_Y"**  
**"fBodyAccJerk_std_Z"**  
**"fBodyGyro_mean_X"**  
**"fBodyGyro_mean_Y"**  
**"fBodyGyro_mean_Z"**  
**"fBodyGyro_std_X"**  
**"fBodyGyro_std_Y"**  
**"fBodyGyro_std_Z"**  
**"fBodyAccMag_mean"**  
**"fBodyAccMag_std"**  
**"fBodyBodyAccJerkMag_mean"**  
**"fBodyBodyAccJerkMag_std"**  
**"fBodyBodyGyroMag_mean"**  
**"fBodyBodyGyroMag_std"**  
**"fBodyBodyGyroJerkMag_mean"**  
**"fBodyBodyGyroJerkMag_std"**  
